# Generated by Django 5.1.3 on 2024-11-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'دوره', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'دانشجوی دوره', 'verbose_name_plural': 'دانشجویان دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='videocourse',
            options={'verbose_name': 'ویدیو', 'verbose_name_plural': 'ویدیو های دوره'},
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='enrollments',
        ),
        migrations.AlterModelTable(
            name='videocourse',
            table='video_courses',
        ),
    ]
