# Generated by Django 5.1.3 on 2024-11-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_end_date_course_start_date_alter_teacher_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.AddField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('in-progress', 'در حال برگزاری...'), ('ended', 'به اتمام رسیده'), ('no-started', 'هنوز شروع نشده')], default='no-started', max_length=15, verbose_name='وضعیت برگزاری دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('free', 'رایگان'), ('paid', 'غیر رایگان')], default='paid', max_length=15, verbose_name='نوع ویدیو'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='وضعیت دوره فعال بودن'),
        ),
    ]
