# Generated by Django 5.1.3 on 2024-11-17 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course.course', verbose_name='دوره مورد نظر'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='description',
            field=models.TextField(verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='duration_in_minutes',
            field=models.PositiveIntegerField(verbose_name='تایم ویدیو'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='order',
            field=models.PositiveIntegerField(verbose_name='شماره جلسه ویدیو'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان ویدیو'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='video_url',
            field=models.URLField(verbose_name='لینک ویدیو'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(choices=[(1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)], decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='course.course', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'db_table': 'course_rating',
                'unique_together': {('course', 'user')},
            },
        ),
    ]
