# Generated by Django 5.1.3 on 2024-11-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_rating_options_alter_rating_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی ویدیو',
                'verbose_name_plural': 'دسته بندی ویدیو ها',
                'db_table': 'video_categories',
            },
        ),
    ]
