# Generated by Django 5.1.3 on 2024-11-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_videocourse_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocourse',
            name='category',
        ),
        migrations.DeleteModel(
            name='VideoCategory',
        ),
    ]
