# Generated by Django 5.1.3 on 2024-11-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_course_course_level_course_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی با ویرگول , جدا شوند'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meta_description',
            field=models.TextField(blank=True, max_length=230, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meta_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان متا در صفحه'),
        ),
    ]
