# Generated by Django 5.1.3 on 2024-11-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_meta_keywords_alter_course_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='course',
            name='meta_title',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='عنوان سئو'),
        ),
    ]
