# Generated by Django 5.1.3 on 2024-11-20 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_course_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ انتشار'),
        ),
    ]
