# Generated by Django 5.1.3 on 2024-11-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, max_length=230, null=True, verbose_name='توضیحات متا سئو'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی با ویرگول , جدا شوند'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان متا در صفحه'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('slug',)},
        ),
    ]
