# Generated by Django 5.1.3 on 2024-11-21 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='تاریخ انتشار'),
        ),
    ]
